name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  test-deploy-dev:
    name: Test & Deploy to Dev
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      ENVIRONMENT: dev
      ENVIRONMENT_URL: https://dev.chiemerie.com
      RELEASE_VERSION: 0.0.0-dev
    secrets: inherit