name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout release action
        uses: actions/checkout@v3
        with:
          repository: chiemerieezechukwu/semantic-release
          ref: main
          path: ./.github/semantic-release
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: ./.github/semantic-release
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
